# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SubmititLauncher
    account: def-six
    gpus_per_node: 1
    cpus_per_task: 4
    mem_gb: 32
    time: 120 # in minutes
    partition: null # Let Slurm decide the partition
    setup:
      - module load StdEnv/2023
      - module load python/3.11.5
      - virtualenv --no-download --system-site-packages ENV --python=python3.11
      - source ENV/bin/activate
      - pip install -r requirements.txt