split: [0, 0, 16] # noise, struct, sem
rank: [8, 8]      # rank_ch, rank_sp

cls:
  _target_: src.models.priors.KPMVNPrior
  tau: 0.0

conditional_cls:
  _target_: src.models.priors.ConditionalKPMVNPrior
  tau: 0.0
  dropout: 0.0
  backbone_features: 256

zero_init:
  _target_: src.utils.prior_init.kpmvn_zero_init
  noise: 0.01

random_init:
  _target_: src.utils.prior_init.kpmvn_random_init
  scale: 1.0
  noise: 0.01
  
class_conditional_init:
  _target_: src.utils.prior_init.kpmvn_simplex_init
  simplex_scale: 1.0
  noise: 0.01