defaults:
  - _self_
  - data: mnist
  - model: glow
  - level_priors: mnist
  - training: default

project:
  name: Discriminative Normalizing Flow
  description: Training a DNF model.

run:
  name: "dnf-run-${now:%Y-%m-%d-%H-%M-%S}"

paths:
  data: ./data
  logs: ./logs

hydra:
  run:
    dir: ${paths.logs}/${run.name}

wandb:
  project: DNF
  entity: e1444-university-of-toronto
  name: "${run.name}"
  group: "MNIST"

logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s: %(message)s"