_target_: src.models.dglow.DGLOWNetwork

in_channels: 1
num_levels: 2
steps_per_level: 6
hidden_channels: 256
bottleneck_channels: 128
num_res_blocks: 3
actnorm_initialization: "identity"
invconv_initialization: "identity"