_target_: src.models.dglow.DGLOWNetwork

in_channels: 1
num_fixed_levels: 3
num_split_levels: 3
steps_per_fixed_level: 4
steps_per_split_level: 16
hidden_channels: 256
bottleneck_channels: 128
num_res_blocks: 3
actnorm_initialization: "identity"
invconv_initialization: "identity"