_target_: src.models.glow.DGLOWNetwork

num_levels: 3
steps_per_level: [2, 2, 2]
hidden_channels: 256
num_blocks: 6
dropout: 0.0
actnorm_initialization: "data-dependent"
invconv_initialization: "orthogonal"
checkpoint_grads: false