_target_: src.models.glow.DGLOWNetwork

num_levels: 3
steps_per_level: [24, 24, 48]
hidden_channels: 128
num_blocks: 1
dropout: 0.0
actnorm_initialization: "data-dependent"
invconv_initialization: "orthogonal"
checkpoint_grads: false