defaults:
  - _self_
  - /scheduler@scheduler: cosine

lr: 1e-3
lr_prior: [0, 0, 0]
lr_prior_channel: [0, 0, 0]
lr_prior_spatial: [0, 0, 0]

gradclip: 1.0
weight_decay: 1e-4
epochs: 20

eval_interval: 1
checkpoint_interval: 5

# Loss and regularization weights
r_logdet: 1e-4
r_aniso: 1e-3
label_smoothing: 0.1

# Scheduler settings
warmup_epochs: 5

# Loss Weights
l_lambda: 0.5     # NLL weight (1.0 - lambda = CE weight)
em_steps: 2

use_ema: false  # Use EMA model for evaluation

ckpt: null
load_model: false
load_prior: false
reset_optimizer: false