defaults:
  - default
  - _self_
  - override /scheduler@scheduler: cosine_wr

epochs: 70
lr: 1e-4
lr_prior: [1e-5, 1e-4, 1e-3]
lr_prior_channel: [1e-5, 1e-4, 1e-3]
lr_prior_spatial: [1e-5, 1e-4, 1e-3]

r_logdet: 0.0
r_aniso: 0.0
label_smoothing: 0.0

# Strict MLE
l_lambda: 1.0
em_steps: 1

nll_dim_reweight: false

use_ema: true

ckpt: null
load_model: true
load_prior: true
reset_optimizer: true