defaults:
  - default
  - _self_
  - override /scheduler@scheduler: cosine

epochs: 20
lr: 3e-4
lr_prior: [5e-5, 5e-5, 5e-5]
lr_prior_channel: [1e-6, 1e-6, 1e-6]
lr_prior_spatial: [0, 0, 0]

# Medium Regularization (Annealing)
r_logdet: 0
r_aniso: 1e-1
label_smoothing: 0.05

# Loss Weights (Transitioning to NLL)
l_lambda: 0.8
em_steps: 0

# Enable EMA
use_ema: true

ckpt: null
load_model: true
load_prior: true
reset_optimizer: true
