defaults:
  - default
  - _self_
  - override /scheduler@scheduler: cosine

epochs: 30
lr: 1e-3
lr_prior: [1e-6, 1e-5, 1e-4]

# High Regularization
r_logdet: 1e-4
label_smoothing: 0.1

# Augmented Lagrangian (Frozen)
use_al: True
log_alpha: -4.0
lr_log_alpha: 0.0
nll_constraint: 0
aug_rho: 1.0